import React from 'react';
import './UserReport.css'; // Importing a separate CSS file for styling

const UserReport = () => {
  return (
    <div className="report-container">
      <h2 className="report-title">Patient Diagnosis and Treatment Plan</h2>
      
      <section className="report-section">
        <h3 className="section-title">Diagnosis</h3>
        <p className="report-text">
          <strong>Acute Infectious Condition</strong> (Based on the symptoms of fever and nausea)
        </p>
      </section>
      
      <section className="report-section">
        <h3 className="section-title">Anomalies</h3>
        <p className="report-text">
          <strong>Sedentary Lifestyle:</strong> This is a risk factor for many diseases including heart disease, 
          which makes the current condition more complex.
        </p>
      </section>

      <section className="report-section">
        <h3 className="section-title">Treatment</h3>
        <ul className="report-list">
          <li>
            <strong>Medical Management:</strong> The patient should immediately consult with their doctor who may prescribe 
            antibiotics to combat the infection. It is crucial to identify the specific pathogen causing the illness 
            for accurate treatment.
          </li>
          <li>
            <strong>Lifestyle Changes:</strong> Given the sedentary lifestyle and heart disease history, the patient should 
            be advised to incorporate regular, low-intensity exercise into their daily routine, such as walking or light 
            resistance training. This can help improve overall cardiovascular health and boost immunity.
          </li>
          <li>
            <strong>Dietary Modifications:</strong> A balanced diet rich in fruits, vegetables, lean proteins, and whole grains 
            is recommended to support the immune system and aid recovery. The doctor may also suggest limiting processed 
            foods, sugars, and saturated fats.
          </li>
          <li>
            <strong>Cardiac Rehabilitation:</strong> Since the patient has a history of heart disease, cardiac rehabilitation 
            programs focusing on exercise training, risk factor management, and counseling should be considered to help 
            manage the heart condition and reduce the risk of complications.
          </li>
          <li>
            <strong>Regular Monitoring:</strong> Close monitoring of blood pressure, cholesterol levels, and overall heart 
            health is essential for the patient's wellbeing during this acute illness and in the recovery period.
          </li>
          <li>
            <strong>Additional Tests:</strong> Given the patient's history, it may be necessary to perform additional tests 
            such as Complete blood count (CBC), electrolyte panel, C-reactive protein (CRP) level, and a possible heart 
            function study (echocardiogram). The doctor will determine which tests are most appropriate based on the 
            specific symptoms and clinical presentation.
          </li>
        </ul>
      </section>

      <footer className="report-footer">
        Generated by Mistral
      </footer>
    </div>
  );
};

export default UserReport;
